version: '2'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
    - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    # depends_on:
    # - zookeeper
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      # KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      # KAFKA_MIN_INSYNC_REPLICAS: 2
      # KAFKA_NUM_PARTITIONS: 20
      # KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      # KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
      # KAFKA_CONTROLLER_SHUTDOWN_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "DevTopic:1:3,PruOneTopic:1:2"
  
  kafka-pub-rest:
    build: .
    ports:
      - "9000:9000"

  # kafkacat:
  #   image: ryane/kafkacat
  #   ports: 
  #     - "10000:10000"
